import pyError
import time

pyError.newError('error', 'error', 'error', 20, 20)

time.sleep(2)

pyError.close()
